#!/bin/bash
DIRECTORY=/reg/d/psdm/cxi/cxic0515/scratch/autosfx/cxic0415/r0100
if [ ! -d "$DIRECTORY" ]; then
  mkdir -p $DIRECTORY
fi

python indexcrystfel/generousBadPixel.py \
exp=cxic0415:run=100 \
-d DscCsPad \
-b 10 \
-o $DIRECTORY

